default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "ncaa_planner_dev") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "ncaa_planner_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "ncaa_planner_prod") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
